In [303]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error

In [304]:
#Loading data

data = pd.read_csv("housing.csv")

In [305]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [306]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [307]:
#Dropping null rows
data = data.dropna()
data = data[data['median_house_value'] <= 500000]

In [308]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19475 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           19475 non-null  float64
 1   latitude            19475 non-null  float64
 2   housing_median_age  19475 non-null  float64
 3   total_rooms         19475 non-null  float64
 4   total_bedrooms      19475 non-null  float64
 5   population          19475 non-null  float64
 6   households          19475 non-null  float64
 7   median_income       19475 non-null  float64
 8   median_house_value  19475 non-null  float64
 9   ocean_proximity     19475 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

Like the main file we will remove median_house_value to "y" and change ocean_proximity to be one-hot encoded instead of being a category like it is now

In [309]:
data_encoded = pd.get_dummies(data, columns=['ocean_proximity'],dtype=int)

In [310]:
data_encoded

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0,1,0,0,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0,1,0,0,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0,1,0,0,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0,1,0,0,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0,1,0,0,0

In [311]:
X = data_encoded.drop('median_house_value', axis=1)
y = data_encoded['median_house_value']

In [312]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [313]:
random_clf = RandomForestRegressor()

In [314]:

#param_grid = {
   # 'n_estimators': [100, 200, 300],
   # 'max_leaf_nodes': [10, 20, 30],
   # 'max_depth': [None, 10, 20, 30]
#}

#grid_random_clf = GridSearchCV(random_clf, param_grid, cv=5)

#grid_random_clf.fit(X_train, y_train)


#best_model = grid_random_clf.best_estimator_

In [315]:
random_clf.fit(X_train, y_train)

RandomForestRegressor()

In [316]:
y_pred_grid = best_model.predict(X_test)

In [317]:
y_pred = random_clf.predict(X_test)

In [318]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
score = random_clf.score(X_test, y_test)

print(f"Root Mean Squared Error for untuned model: {rmse}")
print(f"R^2 Score for untuned model: {score}")

Root Mean Squared Error for untuned model: 44324.322828368386
R^2 Score for untuned model: 0.7971469402360073

In [319]:
#grid_random_clf.best_params_

First iteration:

Root Mean Squared Error for untuned model: 44326.16354355406

R^2 Score for untuned model: 0.7971300915878173

Root Mean Squared Error for tuned model: 57423.541379810034

R^2 Score for tuned model: 0.6595312242555647

Best Params: {'max_depth': None, 'max_leaf_nodes': 30, 'n_estimators': 100}
Will try to change max_leaf_nodes higher and try again. Setting n_estimators and max_depth back to default since that was the best outcome from the Grid Search

In [320]:
#param_grid = {
 #   'max_leaf_nodes': [30,40,50,60,70]
#}

#grid_random_clf = GridSearchCV(random_clf, param_grid, cv=5)

#grid_random_clf.fit(X_train, y_train)


#best_model = grid_random_clf.best_estimator_

In [321]:
#mse_grid = mean_squared_error(y_test, y_pred_grid)
#rmse_grid = np.sqrt(mse_grid)
#score_grid = best_model.score(X_test, y_test)
#print(grid_random_clf.best_params_)

#print(f"Root Mean Squared Error for tuned model: {rmse_grid}")
#print(f"R^2 Score for tuned model: {score_grid}")

Second iteration on tuned model made it a bit better but still not better than default it seems.

{'max_leaf_nodes': 70}
Root Mean Squared Error for tuned model: 57423.541379810034
R^2 Score for tuned model: 0.6999112487451159

Lets try higher values in max_leaf_nodes as well as default "None".

In [ ]:
param_grid = {
    'max_leaf_nodes': [None,70,100,150]
}

grid_random_clf = GridSearchCV(random_clf, param_grid, cv=5)

grid_random_clf.fit(X_train, y_train)


best_model = grid_random_clf.best_estimator_

In [ ]:
mse_grid = mean_squared_error(y_test, y_pred_grid)
rmse_grid = np.sqrt(mse_grid)
score_grid = best_model.score(X_test, y_test)
print(grid_random_clf.best_params_)

print(f"Root Mean Squared Error for tuned model: {rmse_grid}")
print(f"R^2 Score for tuned model: {score_grid}")

Third iteration on tuned model: 
{'max_leaf_nodes': None}
Root Mean Squared Error for tuned model: 53910.85083935326
R^2 Score for tuned model: 0.7986513812917744

Going over to feature engineering the standard RandomForest model instead.